#!/bin/sh

# People's daily 2014 corpus preprocessor

find | grep '\.txt$' | xargs cat | \
	sed 's/\[\([^\/][^]]*\)\]\/[a-z0-9]\+/\1/g;s/ \/[a-z0-9]\+//g;' | \
	sed 's/(/（/g;s/)/）/g;s/!/！/g;s/?/？/g;s/,/，/g;' | \
	sed 's/\([℃，。、：;‘’“”！？…—（）《》「」『』]\)/\1\/w /g;'
